movieproject/movieapp/urls.py
from .import views
from django.urls import path

app_name = 'movieapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('movie/<int:movie_id>/', views.details, name='details'),
    path('add/', views.add, name='add'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
]

movieproject/movieproject/urls.py
from django.contrib import admin
from django.urls import path, include

from movieproject import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('movieapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root = settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=200)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='images')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'img', 'year', 'desc']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm
# Create your views here.
def index(request):
    movie = Movie.objects.all()
    context = {
        'movie_list': movie
    }
    return render(request, 'index.html', context)

def details(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, 'details.html', {'movie': movie})

def add(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        img = request.FILES['img']
        year = request.POST.get('year')
        desc = request.POST.get('desc')
        movie = Movie(name=name, img=img, year=year, desc=desc)
        movie.save()
    return render(request, 'add.html')

def update(request, id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'movie': movie})

def delete(request, id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')



movieproject/templates/add.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>add</title>
</head>
<body>
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>
        Enter Movie Name: <input type="text" name="name" placeholder="Movie Name">
    </p>
    <p>
        Upload Image: <input type="file" name="img">
    </p>
    <p>
        Enter Movie Year: <input type="text" name="year" placeholder="Movie Year">
    </p>
    <p>
        Enter Movie Description: <input type="text" name="desc" placeholder="Movie Description">
    </p>
    <p>
        <input type="submit">
    </p>

</form>
{% endblock %}
</body>
</html>

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>base</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST">
  {% csrf_token %}
    Are you sure to delete this movie?<br>
    <input type="submit">
</form>
</body>
</html>

movieproject/templates/details.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
</head>
<body>
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <img src="{{movie.img.url}}" width="350" height="350">
        </div>
        <div class="col-md-4">
            <h2>{{movie.name}}</h2>
            <h6>Year:{{movie.year}}</h6>
            <h5>{{movie.desc}}</h5>
            <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}
</body>
</html>

movieproject/templates/edit.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit</title>
</head>
<body>
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

</body>
</html>

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}


<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card">
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" height="250px;">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
<!--                    <p class="card-text">{{i.desc}}</p>-->
                    <a href="{% url 'movieapp:details' i.id %}" class="btn btn-primary">View</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<!--{% for i in movie_list %}-->
<!--<img src="{{i.img.url}}" width="200" height="200">-->
<!--<a href="{% url 'movieapp:details' i.id %}">{{i.name}}</a><br>-->
<!--{% endfor %}-->

<!--style="width: 18rem;"-->

{% endblock %}